"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# MUST CHANGE THIS!!!!!!
# Make this the registered name of your application, in snake case
APPLICATION_NAME = 'referrals'

# -----------------------------------------------------------------------------
##### Base Settings #####
# -----------------------------------------------------------------------------

BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# https://docs.djangoproject.com/en/3.0/ref/settings/#secret-key
SECRET_KEY = '+3*tp4^@m6(ebgq3y!!@xbwwnr4jvh7_t12g-6dta2d6&*(dho'

# https://docs.djangoproject.com/en/3.0/ref/settings/#debug
DEBUG = True

# https://docs.djangoproject.com/en/3.0/ref/settings/#allowed-hosts
ALLOWED_HOSTS = []


# -----------------------------------------------------------------------------
##### Application Settings #####
# -----------------------------------------------------------------------------

# https://docs.djangoproject.com/en/3.0/ref/settings/#installed-apps
DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
THIRD_PARTY_APPS = [
    'rest_framework',
    'oauth2_provider',
]
LOCAL_APPS = [
    'referrals'
]
INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

# https://docs.djangoproject.com/en/3.0/ref/settings/#middleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# https://docs.djangoproject.com/en/3.0/ref/settings/#templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# -----------------------------------------------------------------------------
##### File Configurations #####
# -----------------------------------------------------------------------------

# https://docs.djangoproject.com/en/3.0/ref/settings/#root-urlconf
ROOT_URLCONF = 'referrals.urls'

# https://docs.djangoproject.com/en/3.0/ref/settings/#wsgi-application
WSGI_APPLICATION = 'referrals.wsgi.application'


# -----------------------------------------------------------------------------
##### Database #####
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases
# -----------------------------------------------------------------------------

# https://docs.djangoproject.com/en/3.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# https://docs.djangoproject.com/en/3.0/ref/settings/#database-routers
DATABASE_ROUTERS = []


# -----------------------------------------------------------------------------
##### Password validation #####
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators
# -----------------------------------------------------------------------------

# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# -----------------------------------------------------------------------------
##### Internationalization #####
# https://docs.djangoproject.com/en/3.0/topics/i18n/
# -----------------------------------------------------------------------------

# https://docs.djangoproject.com/en/3.0/ref/settings/#language-code
LANGUAGE_CODE = 'en-us'

# https://docs.djangoproject.com/en/3.0/ref/settings/#std:setting-TIME_ZONE
TIME_ZONE = 'UTC'

# https://docs.djangoproject.com/en/3.0/ref/settings/#use-i18n
USE_I18N = True

# https://docs.djangoproject.com/en/3.0/ref/settings/#use-l10n
USE_L10N = True

# https://docs.djangoproject.com/en/3.0/ref/settings/#use-tz
USE_TZ = True


# -----------------------------------------------------------------------------
##### Static files (CSS, JavaScript, Images) #####
# https://docs.djangoproject.com/en/3.0/howto/static-files/
# -----------------------------------------------------------------------------

# https://docs.djangoproject.com/en/3.0/ref/settings/#static-url
STATIC_URL = '/static/'

# -----------------------------------------------------------------------------
##### Media Files #####
# All media settings must be defined in their specific environment's file
# -----------------------------------------------------------------------------


# -----------------------------------------------------------------------------
##### Email #####
# -----------------------------------------------------------------------------

# https://docs.djangoproject.com/en/3.0/ref/settings/#email-backend
# Log emails to the console. If emails are needed, define the email backend in
#   the production settings file.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# -----------------------------------------------------------------------------
##### REST Framework Settings #####
# https://www.django-rest-framework.org/api-guide/settings/
# -----------------------------------------------------------------------------

# https://www.django-rest-framework.org/api-guide/settings/#api-reference
REST_FRAMEWORK = {
    # https://www.django-rest-framework.org/api-guide/settings/#default_authentication_classes
    # https://django-oauth-toolkit.readthedocs.io/en/latest/rest-framework/rest-framework.html
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        'rest_framework.authentication.SessionAuthentication',
    ),

    # https://www.django-rest-framework.org/api-guide/settings/#default_permission_classes
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),

    # --------------------
    ##### Pagination #####
    # --------------------
    # https://www.django-rest-framework.org/api-guide/settings/#default_pagination_class
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    # https://www.django-rest-framework.org/api-guide/settings/#page_size
    'PAGE_SIZE': 50,
}


# -----------------------------------------------------------------------------
##### Django OAuth2 Toolkit (oauth2_provider) #####
# https://django-oauth-toolkit.readthedocs.io/en/latest/settings.html
# -----------------------------------------------------------------------------

# Put the development ID and Secret here
_resource_server_client_id = ''
_resource_server_client_secret = ''
# NOTE: The production Client ID and Client Secret should be defined in environment variables, not hard-coded
OAUTH2_PROVIDER = {
    # https://django-oauth-toolkit.readthedocs.io/en/latest/settings.html#resource-server-introspection-url
    'RESOURCE_SERVER_INTROSPECTION_URL': "http://localhost:8000/api/auth/o/introspect/",

    # https://django-oauth-toolkit.readthedocs.io/en/latest/settings.html#resource-server-introspection-credentials
    'RESOURCE_SERVER_INTROSPECTION_CREDENTIALS': (
        os.environ.get('DJANGO_OAUTH2_PROVIDER_RESOURCE_SERVER_INTROSPECTION_CREDENTIALS_CLIENT_ID', _resource_server_client_id),
        os.environ.get('DJANGO_OAUTH2_PROVIDER_RESOURCE_SERVER_INTROSPECTION_CREDENTIALS_CLIENT_SECRET', _resource_server_client_secret)
    ),

    # https://django-oauth-toolkit.readthedocs.io/en/latest/settings.html#resource-server-token-caching-seconds
    # There is currently a bug with the following setting. At this time, Revibe
    #   developers are still awaiting a fix from the package contributors.
    # 'RESOURCE_SERVER_TOKEN_CACHING_SECONDS': 1800 # in seconds
}
