# Generated by Django 3.0.8 on 2020-08-05 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of new user.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referree', models.OneToOneField(help_text='the new user who was referred to Revibe.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referree', to=settings.AUTH_USER_MODEL, verbose_name='referred')),
                ('referrer', models.ForeignKey(help_text='The user who referred a new user to Revibe.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrer', to=settings.AUTH_USER_MODEL, verbose_name='sent')),
            ],
            options={
                'verbose_name': 'referral',
                'verbose_name_plural': 'referrals',
            },
        ),
    ]
